### ISSUE TITLE
skin下文件名末尾多了一个字符'b'

### ISSUE THREAD

**Issue by TrymenT-AlphA** [yuanyan3060/Arknights-Bot-Resource#10]
![屏幕截图 2022-10-24 203221](https://user-images.githubusercontent.com/70501769/197526254-4feaedf2-6edd-46c0-95d3-3ba94a7ee293.png)

**Comment by yuanyan3060** [comment]
这个不是bug，是特性(确信)
有b和没b是用来区分图像大小的，仓库只提供有b的版本
