### ISSUE TITLE
building_data.json格式错误，仍为二进制格式

### ISSUE THREAD

**Issue by SleepyAsh0191** [yuanyan3060/Arknights-Bot-Resource#7]
![c2c28bfa1fce261069a91337273efd7a](https://user-images.githubusercontent.com/64446140/189025829-e928e106-9b25-434f-8381-27c95cb2b0c3.png)
rt

**Comment by MistEO** [comment]
+1，泰迪——

**Comment by yuanyan3060** [comment]
bug原因:yj格式不规范
已修复(代码更丑了 呜)

**Comment by SleepyAsh0191** [comment]
感谢！
